# Generated by Django 3.2.10 on 2022-08-06 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('headline', models.CharField(max_length=255)),
                ('theaser', models.CharField(max_length=255)),
                ('theaseranswer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='registieren',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benutzername', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('repeatpassword', models.CharField(max_length=255)),
            ],
        ),
    ]
